// const API = "http://107.167.80.37:8000";
const API = "https://hufi.loca.lt"
const APIRoom = API+"/manager/room"
const APILogin = API+"/user/login"
const APITypeRoom = API+"/manager/type-room";
const APIEmployee = API+"/user/"
const APIService = API+"/manager/service";
const APIDevice = API+"/manager/hotel-device";
const APICustomer = API+"/manager/customer";
const APIDetailType = API+"/manager/detail-type";
const APIRole = API + "/manager/role";
const APIDelegation = API + "/manager/delegation";
const APIBookingRoom = API + "/manager/register";
const APICheckInRoom = API + "/manager/check-in/"
const APICancel = API + "/manager/cancel/"
const APICheckOutRoom = API + "/manager/check-out/"
const APIUseServiceDevice = API + "/manager/use/"
const APIBill = API + "/manager/bill/"
const APITurnover = API + "/manager/turnover"
const APIClean = API + "/manager/scheduling"
export {APIClean,APITurnover,APIBill,APICancel,APICheckInRoom,APIRoom,APITypeRoom,APIService,APILogin,APIEmployee,APIDevice,APICustomer,APIDetailType,APIRole,APIDelegation,APIBookingRoom,APIUseServiceDevice,APICheckOutRoom};